### ISSUE TITLE
Installation: List dependencies in README, deprecated brew command.

### ISSUE THREAD

**Issue by balboa2** [boltops-tools/homebrew-software#1]
First of all, thanks for developing Terraspaces!

I wanted to address a minor discovery during manual installation: 

1. `brew cask <command>` was deprecated in favor of `brew <command> --cask` in Homebrew 2.6.0. Now that 2.7.0 has been released, they have been disabled.  https://github.com/Homebrew/discussions/discussions/340

`Error: Calling brew cask install is disabled! Use brew install [--cask] instead.`

**Comment by tongueroo** [comment]
Readme updated. Thanks.
