### ISSUE TITLE
Error on last version: Could not find activesupport-6.1.3.1 in any of the sources

### ISSUE THREAD

**Issue by Mayeu** [boltops-tools/homebrew-software#2]
Hello,

I'm suddenly having an issue to run Terraspace on my mac (10.15.7):

```
➜ terraspace --version
Could not find activesupport-6.1.3.1 in any of the sources
Run `bundle install` to install missing gems.
```

Running `bundle install` don't change anything, and I do see the gem in the list:
```
➜ bundle install
Using rake 13.0.3
Using concurrent-ruby 1.1.8
Using i18n 1.8.10
Using minitest 5.14.4
Using tzinfo 2.0.4
Using zeitwerk 2.4.2
Using activesupport 6.1.3.1
[...]
```

**Comment by Mayeu** [comment]
Ha, running `bundle update` in the repository does solve the issue.

Maybe that should be documented somewhere?

**Comment by tongueroo** [comment]
Here you go: https://terraspace.cloud/docs/install/updating/
