### ISSUE TITLE
[Question] Where can I find the MacOS package?

### ISSUE THREAD

**Issue by BeyondEvil** [boltops-tools/homebrew-software#3]
I need to automate the installation of Terraspace on a Mac and I can't use Homebrew.

Where can I find a suitable tar or pkg file?

Thanks 🙏

**Comment by tongueroo** [comment]
Seeing this now. Here you go:

* https://tap.boltops.com/packages/terraspace/terraspace-latest.dmg

Got it from the docs:

* https://terraspace.cloud/docs/install/standalone/macosx/
